name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: fedora
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare container
        run: sudo dnf -y install podman
      -
        name: Build linux 
        run: ./build.sh 