name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    # Containers must run in Linux based operating systems
    runs-on: fcos
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare container
        run: sudo dnf -y install podman which
      -
        name: Build linux 
        run: ./build.sh 3.x mono-6.12.0.147